const modalTypes = {
  OPEN_SIGN_UP_MODAL: 'OPEN_SIGN_UP_MODAL',
  OPEN_LOGIN_MODAL: 'OPEN_LOGIN_MODAL',
  OPEN_SELECT_DATE_MODAL: 'OPEN_SELECT_DATE_MODAL',
  OPEN_PLAYER_GAME_PROJECTION_STATS_MODAL: 'OPEN_PLAYER_GAME_PROJECTION_STATS_MODAL',

  CLOSE_MODALS: 'CLOSE_MODALS',
};

export default modalTypes;
